display_name: Bettbox

packager: appshub
packagerEmail: appshubcc@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - Bettbox
  - Clash
  - ClashMeta
  - Proxy

generic_name: Bettbox

group: Applications/Internet

startup_notify: true