name: Android Debug Build

on:
  workflow_dispatch:
  push:

jobs:
  debug-build:
    name: Build Flutter Android Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
          cache-dependency-path: core/go.sum
          cache: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.x'
          cache: true

      - name: Setup Pub Cache
        uses: actions/cache@v5
        with:
          path: \~/.pub-cache
          key: flutter-pub-\( {{ runner.os }}- \){{ hashFiles('pubspec.lock') }}
          restore-keys: |
            flutter-pub-${{ runner.os }}-

      - name: Build Debug APK
        run: |
          flutter pub get
          rm -rf .dart_tool/build
          dart run build_runner build --delete-conflicting-outputs
          dart setup.dart android --arch universal --out core
          flutter build apk --debug --dart-define=APP_ENV=pre --dart-define=SENTRY_DSN=dummy_dsn

      - name: Rename APK with timestamp
        id: apk
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          mv build/app/outputs/flutter-apk/app-debug.apk "bettbox-debug-${TIMESTAMP}.apk"
          echo "name=bettbox-debug-${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Upload Debug APK
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.apk.outputs.name }}
          path: ${{ steps.apk.outputs.name }}.apk
          retention-days: 1
          archive: false
          if-no-files-found: error
